//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frameset
    {
        public int frameId { get; set; }
        public string frameName { get; set; }
        public string frameType { get; set; }
        public Nullable<decimal> framePrice { get; set; }
        public Nullable<int> frameQuantity { get; set; }
    }
}
